myfile=open("atharva.txt","r")
str1 = myfile.read(10)
str2 = myfile.readline(5)
str3 = myfile.readlines()
print("output of first read : ")
print(str1)
print("output of second read : ")
print(str2)
print("output of third read : ")
print(str3)
