a = []
b = input("marks : ")
a.append(b)
c = input("marks : ")
a.append(c)
d = input("marks : ")
a.append(d)
e = input("marks : ")
a.append(e)
f = input("marks : ")
a.append(f)
g = input("marks : ")
a.append(g)
print(a)